print("please enter the folllowing information;")
print()
first_name = input("first name;")
last_name = input("last name;")
Email_address = input("email address;")
Phone_number = input("phone number;")
Job_title = input("job title;")
ID_Number = input("ID number;")

print("\nThe ID Card is:")
print("______________________________")
print(f"{last_name.upper()}, {first_name.capitalize()}")
print(f"{Job_title.title()}")
print(f"ID Number: {ID_Number}")
print()
print(f"Email: {Email_address.lower()}")
print(f"Phone: {Phone_number}")
print("______________________________")
